name: Test Workflow

on: [push]

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./bootstrap

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
          cache-dependency-path: ./bootstrap/package-lock.json

      - name: Install
        run: npm ci

      - name : echo & liste des fichiers
        run: |
          echo "Hello Github Actions"
          git ls-files

      - name: Linter (Qualité du code)
        run: npm run eslint:check

      - name: Tests Unitaires (Logique mathématique)
        run: npm run mocha:test

      - name: Couverture de code
        run: npm run nyc:run







